name: PeopleStrong Punch-In

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1-5'  # 8:30 AM IST, Mon–Fri

jobs:
  punch_in:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements.txt found, skipping..."

      - name: Run punchin.py
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python punchin.py
