name: Punch-In Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_punchin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium  # Install Selenium directl

      - name: Run punchin.py script
        run: |
          cd punchinnn  # Navigate to the directory where punchin.py is located
          python punchin.py  # Run the Python script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
